import { ILanguage } from './Translation';
export const es: ILanguage = {
	welcome: 'Bienvenidos a',
	clicSubtitle: 'Dale clic a asterius para que podamos pedir un deseo',
	isAsteriusInvoking: 'Asterious esta siendo invocado, esperemos a que conteste',
	asteriusInvoked: 'Asterious ha sido invocado, pidamos nuestro deseo',
	content: 'Contenido en proceso',
	login: 'Iniciar sesión',
	loginlabel: 'Ingresa tu nick',
	loginhint: 'Presione enter para ingresar',
	loginError1: 'El usuario que ingresaste no existe, prueba con otro!',
	loginError2: 'Para ingresar necesitas un usuario, prueba registrandote',
	register: 'Registrarse',
	registerLabel: 'Registra tu nick',
	registerhint: 'Presione enter para registrar nick',
	registerError1: 'El usuario que ingresaste ya existe, prueba con otro!',
	registerError2: 'Para registrarse necesitas un usuario, prueba de nuevo',
	navHome: 'Inicio',
	footerOwner: 'creador del sitio',
	footerBackGround: 'El fondo fue ilustrado por vectorpouch',
	lang: 'Idioma',
};
